REAL_10K_SNP_1000G_PATH = "resource/10K_SNP_1000G_real.hapt"
REAL_EXTRA_DATA_PATH = "resource/extra_data_1000G.tsv"
DEFAULT_RESULTS_FOLDER = "experiment_results"
SAMPLE_COLUMN_NAME = "Sample name"
DEFAULT_LATENT_SIZE = 600  # size of noise input
DEFAULT_ALPH = 0.01  # alpha value for LeakyReLU
DEFAULT_GENERATOR_LEARNING_RATE = 0.0001  # generator learning rate
DEFAULT_DISCRIMINATOR_LEARNING_RATE = 0.0008  # discriminator learning rate
DEFAULT_EPOCHS = 10001
DEFAULT_BATCH_SIZE = 256
DEFAULT_SAVE_NUMBER = 500  # epoch interval for saving outputs
DEFAULT_CLASS_LOSS_WEIGHTS = 1
DEFAULT_MINIMUM_SAMPLES = 10
DEFAULT_FIRST_EPOCH = 1
DEFAULT_TARGET_COLUMN = "Superpopulation code"
DEFAULT_EXPERIMENT_NAME = "default_gs-ac-gan"
SEQUENCE_RESULTS_PATH = "fake_genotypes_sequences/new_sequences"
NUMBER_OF_EXPERIMENT_SAMPLES = 2000
DEFAULT_EXPERIMENT_OUTPUT_DIR = "comparison_model_tests"
REAL_POSITION_FILE_NAME = "resource/10k_SNP.legend"
